name: Push latest version to DockerHub

on:
  push:
    branches: [master]
    paths-ignore:
      - "README.md"
      - ".github/workflows/release.yml"

env:
  TARGET_BASE: base
  TARGET_APP: app
  DOCKER_BUILDKIT: 1

jobs:
  example:
    name: docker
    runs-on: linux-self-hosted
    strategy:
      matrix:
        include:
          - NEXUS_CACHED_TAG_PREFIX: "localhost:8082/nexus-ops:example"
            DOCKERHUB_FULL_TAG: "unfor19/nexus-ops:example"
            DOCKERFILE_PATH: Dockerfile.example
    steps:
      - uses: actions/checkout@v2
      - name: pull images
        run: |
          docker pull localhost:8082/unfor19/alpine-ci:latest && \
          docker pull localhost:8082/ubuntu:20.04
      - name: tag images
        run: |
          docker tag "localhost:8082/unfor19/alpine-ci:latest" "unfor19/alpine-ci:latest" && \
          docker tag "localhost:8082/ubuntu:20.04"  "ubuntu:20.04"
      - name: build image
        run: |
          docker build . -t "${{ matrix.DOCKERHUB_FULL_TAG }}" \
            -f "${{ matrix.DOCKERFILE_PATH }}" \
            --target "${TARGET_APP}" \
            --build-arg BUILDKIT_INLINE_CACHE=1
      - name: test image
        run: |
          docker run --rm "${{ matrix.DOCKERHUB_FULL_TAG }}"
      - name: push to dockerhub
        run: |
          docker push "${{ matrix.DOCKERHUB_FULL_TAG }}"
  app:
    # Assumes that nexus is running locally
    name: docker
    runs-on: linux-self-hosted
    strategy:
      matrix:
        include:
          - DOCKERHUB_FULL_TAG: "unfor19/nexus-ops"
            DOCKERFILE_PATH: Dockerfile
    steps:
      - uses: actions/checkout@v2
      - name: build image
        run: |
          docker build . -t "${{ matrix.DOCKERHUB_FULL_TAG }}" \
            -f "${{ matrix.DOCKERFILE_PATH }}" \
            --target "${TARGET_APP}" \
            --build-arg BUILDKIT_INLINE_CACHE=1
      - name: push to dockerhub
        run: |
          docker push "${{ matrix.DOCKERHUB_FULL_TAG }}"
